import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "@/sections/Footer";
import Header from "@/sections/Header";
import { AuthProvider } from "@/shared/context/AuthContext/AuthContext";
import Main from "@/sections/Main";
import Wrapper from "@/sections/Wrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Atlant trade",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        cz-shortcut-listen="true"
        // suppressHydrationWarning={false}
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <AuthProvider>
      <Wrapper>
        <Header />
        <Main>
          {children}
        </Main>
        <Footer />
      </Wrapper>
      </AuthProvider>

      </body>
    </html>
  );
}
